[workspace]
members = ["contracts/*", "packages/*"]

[profile.release.package.sg-name]
codegen-units = 1
incremental = false

[profile.release.package.name-minter]
codegen-units = 1
incremental = false

[profile.release.package.sg721-name]
codegen-units = 1
incremental = false

[profile.release.package.marketplace]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
