/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Decimal = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export interface InstantiateMsg {
  collection_info: CollectionInfoForRoyaltyInfoResponse;
  minter: string;
  name: string;
  symbol: string;
}
export interface CollectionInfoForRoyaltyInfoResponse {
  creator: string;
  description: string;
  explicit_content?: boolean | null;
  external_link?: string | null;
  image: string;
  royalty_info?: RoyaltyInfoResponse | null;
  start_trading_time?: Timestamp | null;
}
export interface RoyaltyInfoResponse {
  payment_address: string;
  share: Decimal;
}
export type ExecuteMsg = {
  create_site: {
    name: string;
  };
} | {
  update_info: {
    bio?: string | null;
    name: string;
    profile_banner?: NFT | null;
    profile_picture?: NFT | null;
  };
} | {
  update_layout: {
    layout: Row[];
  };
};
export type Addr = string;
export type LayoutContent = {
  n_f_t_display: NFTDisplayType;
} | {
  text_box: TextBoxType;
} | {
  spark_donation: SparkDonationType;
};
export interface NFT {
  collection: Addr;
  token_id: string;
}
export interface Row {
  columns: number;
  items: LayoutItem[];
  row: number;
}
export interface LayoutItem {
  col_span: number;
  content: LayoutContent;
  subtitle?: string | null;
  title: string;
}
export interface NFTDisplayType {
  nfts: NFT[];
}
export interface TextBoxType {
  button?: Button | null;
  text: string;
}
export interface Button {
  href: string;
  text: string;
}
export interface SparkDonationType {
  campaign: string;
}
export type QueryMsg = {
  site: {
    address: string;
  };
} | {
  params: {};
};
export type Uint128 = string;
export interface ParamsResponse {
  fair_burn_percent: Decimal;
  fee_account: string;
  sg721_name_contract_addr: string;
  site_creation_fee: Uint128;
}
export interface SiteResponse {
  site: Site;
}
export interface Site {
  bio?: string | null;
  layout: Row[];
  name: string;
  profile_banner?: NFT | null;
  profile_picture?: NFT | null;
}